default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wysebits_api_development

test:
  <<: *default
  database: wysebits_api_test
production:
  <<: *default
  database: wysebits_api_production
  username: wysebits_api
  password: <%= ENV['WYSEBITS_API_DATABASE_PASSWORD'] %>
